[context.production.environment]
API_URL           = "https://chords-api.herokuapp.com"

[context.dev.environment]
API_URL           = "https://chords-api-dev.herokuapp.com"

[[redirects]]
  from = "https://public.cadencechords.com/*"
  to = "https://public.mezzochords.com/:splat"
  status = 301
  force = true